name: Discord Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # 3時間おきに自動実行（UTC時間なので注意）
    - cron: '0 */3 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: pip install -r requirements.txt

      - name: Run
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: python main.py
